# Generated by Django 5.2.10 on 2026-02-25 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_productrecommendation'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес ресторана')),
                ('working_hours', models.CharField(max_length=100, verbose_name='График работы (напр. 10:00-22:00)')),
                ('location_coords', models.CharField(blank=True, max_length=100, verbose_name='Координаты для карты')),
            ],
            options={
                'verbose_name': 'Настройки ресторана',
            },
        ),
        migrations.AlterModelOptions(
            name='productrecommendation',
            options={'verbose_name': 'Рекомендация ИИ'},
        ),
    ]
