# Generated by Django 5.2.10 on 2026-02-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_restaurantconfig_alter_productrecommendation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fiscal_fd',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер ФД'),
        ),
        migrations.AddField(
            model_name='order',
            name='fiscal_fn',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер ФН'),
        ),
        migrations.AddField(
            model_name='order',
            name='fiscal_fp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Фискальный признак ФП'),
        ),
        migrations.AddField(
            model_name='order',
            name='fiscal_kkt',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя ККТ'),
        ),
    ]
