# Generated by Django 5.2.10 on 2026-03-05 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_order_fiscal_fd_order_fiscal_fn_order_fiscal_fp_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurantconfig',
            options={'verbose_name': 'Настройки ресторана', 'verbose_name_plural': 'Настройки ресторана'},
        ),
        migrations.AddField(
            model_name='address',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='address',
            name='lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота'),
        ),
        migrations.AddField(
            model_name='order',
            name='courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to=settings.AUTH_USER_MODEL, verbose_name='Назначенный доставщик'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_order_index',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядок в маршруте'),
        ),
        migrations.AddField(
            model_name='profile',
            name='current_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Текущая широта'),
        ),
        migrations.AddField(
            model_name='profile',
            name='current_lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Текущая долгота'),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('client', 'Клиент'), ('courier', 'Доставщик')], default='client', max_length=10, verbose_name='Роль'),
        ),
        migrations.AddField(
            model_name='restaurantconfig',
            name='name',
            field=models.CharField(default='GINZA', max_length=100, verbose_name='Название филиала'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('cooking', 'Готовится'), ('ready', 'Готов к выдаче'), ('delivering', 'В пути'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='restaurantconfig',
            name='location_coords',
            field=models.CharField(blank=True, max_length=100, verbose_name='Координаты (широта, долгота)'),
        ),
    ]
