# Generated by Django 5.2.10 on 2026-03-06 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_restaurantconfig_options_address_lat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='current_lat',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='current_lng',
        ),
        migrations.AddField(
            model_name='profile',
            name='last_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
