# Generated by Django 5.2.10 on 2026-03-30 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_supportmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='calories',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Калорийность (ккал)'),
        ),
    ]
