# Generated by Django 5.2.10 on 2026-04-13 14:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_profile_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='calories',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2000)], verbose_name='Калорийность (ккал)'),
        ),
    ]
