# Generated by Django 5.2.10 on 2026-04-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_product_calories'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_time',
            field=models.DateTimeField(blank=True, help_text='Выберите дату и время, когда вам удобно получить заказ', null=True, verbose_name='Желаемое время доставки'),
        ),
    ]
