# Generated by Django 5.2.10 on 2026-04-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_order_delivery_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='Онлайн'),
        ),
    ]
