# Generated by Django 5.2.10 on 2026-04-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_profile_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportmessage',
            name='is_from_admin',
            field=models.BooleanField(default=False, verbose_name='Отправлено оператором'),
        ),
    ]
