# Generated by Django 5.2.10 on 2026-04-24 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_supportmessage_is_from_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_operator_viewed',
            field=models.BooleanField(default=False, verbose_name='Оператор просмотрел'),
        ),
    ]
