# Generated by Django 5.2.10 on 2026-04-26 19:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_order_is_operator_viewed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='lat',
            field=models.FloatField(blank=True, help_text='Автоматически определятся при создании заказа', null=True, verbose_name='Широта адреса доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота адреса доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='route_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Рассчитывается автоматически для курьера', verbose_name='Порядок в оптимальном маршруте'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'courier', 'route_order'], name='main_order_status_373877_idx'),
        ),
    ]
