# Generated by Django 5.2.10 on 2026-04-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_order_lat_order_lng_order_route_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_time',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_time_from',
            field=models.DateTimeField(blank=True, help_text='Начало интервала, когда вам удобно получить заказ', null=True, verbose_name='Желаемое время доставки (с)'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_time_to',
            field=models.DateTimeField(blank=True, help_text='Конец интервала доставки', null=True, verbose_name='Желаемое время доставки (по)'),
        ),
    ]
