# Generated by Django 5.2.10 on 2026-05-01 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_remove_order_delivery_time_order_delivery_time_from_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название скидки')),
                ('discount_type', models.CharField(choices=[('percent', 'Процент'), ('fixed', 'Фиксированная сумма')], default='percent', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, help_text='Процент или сумма в рублях', max_digits=10, verbose_name='Значение')),
                ('applies_to', models.CharField(choices=[('all', 'Всё меню'), ('category', 'Категория'), ('product', 'Конкретное блюдо')], default='all', max_length=20)),
                ('active', models.BooleanField(default=True, verbose_name='Активна')),
                ('start_date', models.DateTimeField(verbose_name='Начало действия')),
                ('end_date', models.DateTimeField(verbose_name='Конец действия')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Скидка',
                'verbose_name_plural': 'Скидки',
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('new', 'Новый'), ('cooking', 'Готовится'), ('ready', 'Готов к выдаче'), ('delivering', 'В пути'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], max_length=20)),
                ('new_status', models.CharField(choices=[('new', 'Новый'), ('cooking', 'Готовится'), ('ready', 'Готов к выдаче'), ('delivering', 'В пути'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'История статуса заказа',
                'verbose_name_plural': 'Истории статусов заказов',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='dish_type',
            field=models.CharField(choices=[('salad', 'Салат'), ('soup', 'Суп'), ('main', 'Горячее блюдо'), ('side', 'Гарнир'), ('sauce', 'Соус'), ('drink', 'Напиток'), ('dessert', 'Десерт'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип блюда'),
        ),
        migrations.AddField(
            model_name='productrecommendation',
            name='pairing_type',
            field=models.CharField(blank=True, help_text='Тип сочетания: salad_main, main_salad, soup_bread и т.д.', max_length=50),
        ),
        migrations.AddField(
            model_name='productrecommendation',
            name='source_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.category'),
        ),
        migrations.AddField(
            model_name='productrecommendation',
            name='source_type',
            field=models.CharField(choices=[('product', 'Продукт'), ('category', 'Категория'), ('user', 'Пользователь')], default='product', max_length=20),
        ),
        migrations.AddField(
            model_name='productrecommendation',
            name='source_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_messages', to='main.order', verbose_name='Связанный заказ (если есть)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='lat',
            field=models.FloatField(blank=True, help_text='Автоматически определяется при создании заказа', null=True, verbose_name='Широта адреса доставки'),
        ),
        migrations.AlterField(
            model_name='productrecommendation',
            name='source_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_prod', to='main.product'),
        ),
        migrations.AddIndex(
            model_name='productrecommendation',
            index=models.Index(fields=['source_type', 'source_product'], name='main_produc_source__d3c8b4_idx'),
        ),
        migrations.AddIndex(
            model_name='productrecommendation',
            index=models.Index(fields=['source_type', 'source_category'], name='main_produc_source__406776_idx'),
        ),
        migrations.AddIndex(
            model_name='productrecommendation',
            index=models.Index(fields=['source_type', 'source_user'], name='main_produc_source__7f91be_idx'),
        ),
        migrations.AddField(
            model_name='discount',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Категория (если applies_to=category)'),
        ),
        migrations.AddField(
            model_name='discount',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.product', verbose_name='Блюдо (если applies_to=product)'),
        ),
        migrations.AddField(
            model_name='orderstatushistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил'),
        ),
        migrations.AddField(
            model_name='orderstatushistory',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='main.order'),
        ),
    ]
