# Generated by Django 5.2.10 on 2026-05-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_discount_orderstatushistory_product_dish_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatushistory',
            name='old_status',
            field=models.CharField(blank=True, choices=[('new', 'Новый'), ('cooking', 'Готовится'), ('ready', 'Готов к выдаче'), ('delivering', 'В пути'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], max_length=20, null=True),
        ),
    ]
