# Generated by Django 5.2.10 on 2026-05-02 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_orderstatushistory_old_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportmessage',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_messages', to='main.order'),
        ),
    ]
