# Generated by Django 5.2.10 on 2026-05-02 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_supportmessage_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0, verbose_name='Вес рекомендации')),
                ('pairing_type', models.CharField(blank=True, max_length=50, verbose_name='Тип сочетания (salad_main и т.п.)')),
            ],
            options={
                'verbose_name': 'Элемент рекомендации',
                'verbose_name_plural': 'Элементы рекомендаций',
            },
        ),
        migrations.AlterModelOptions(
            name='productrecommendation',
            options={'verbose_name': 'Рекомендация', 'verbose_name_plural': 'Рекомендации'},
        ),
        migrations.RemoveIndex(
            model_name='productrecommendation',
            name='main_produc_source__d3c8b4_idx',
        ),
        migrations.RemoveIndex(
            model_name='productrecommendation',
            name='main_produc_source__406776_idx',
        ),
        migrations.RemoveIndex(
            model_name='productrecommendation',
            name='main_produc_source__7f91be_idx',
        ),
        migrations.AlterUniqueTogether(
            name='productrecommendation',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='productrecommendation',
            name='source_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations_as_source', to='main.product'),
        ),
        migrations.AddField(
            model_name='recommendationitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product'),
        ),
        migrations.AddField(
            model_name='recommendationitem',
            name='recommendation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.productrecommendation'),
        ),
        migrations.AddField(
            model_name='productrecommendation',
            name='recommended_products',
            field=models.ManyToManyField(related_name='recommendations_as_target', through='main.RecommendationItem', to='main.product', verbose_name='Рекомендуемые товары'),
        ),
        migrations.RemoveField(
            model_name='productrecommendation',
            name='pairing_type',
        ),
        migrations.RemoveField(
            model_name='productrecommendation',
            name='recommended_product',
        ),
        migrations.RemoveField(
            model_name='productrecommendation',
            name='score',
        ),
        migrations.AlterUniqueTogether(
            name='recommendationitem',
            unique_together={('recommendation', 'product')},
        ),
    ]
